<a href="https://colab.research.google.com/github/daeyeong8855/Image-Manipulation-and-Dataset-Construction/blob/main/%EB%B2%94%EC%A3%BC%ED%98%95_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##순서없는 범주형 데이터 처리
명목척도

In [7]:
import numpy as np
from sklearn.preprocessing import LabelBinarizer, MultiLabelBinarizer

feature = np.array((['가나다라'],
                    ['가나다라'],
                    ['아바하자'],
                    ['카나다사']))


one_hot = LabelBinarizer() #원-핫 인코더 생성
one_hot.fit_transform(feature) #특성을 원 핫 인코딩 변환
print (one_hot.classes_) #특성 클래스 확인

['가나다라' '아바하자' '카나다사']


### 다중 클래스 특성에 대한 처리

In [9]:
multiclass_feature = [('가나다라마', '아사바하나'),
                      ('자나다라마', '아자바하나'),
                      ('카나다라마', '아파바하나'),
                      ('파나다라마', '아라바하나'),
                      ('가나다라마', '아타바하나')]

one_hot_mult = MultiLabelBinarizer()
one_hot_mult.fit_transform(multiclass_feature)

print(one_hot_mult.classes_)
                      

['가나다라마' '아라바하나' '아사바하나' '아자바하나' '아타바하나' '아파바하나' '자나다라마' '카나다라마' '파나다라마']


## 문자열 타깃 데이터 원-핫 인코딩

In [12]:
from sklearn.preprocessing import OneHotEncoder
str_feature = ([['안녕', 1],
                ['저녁', 2],
                ['점심', 3]])


one_hot_encoder = OneHotEncoder(sparse=False)

# 입력특성배열을 모두 범주형으로
print(one_hot_encoder.fit_transform(str_feature))

[[1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


## 서열척도 인코딩

In [31]:
import pandas as pd

dataframe = pd.DataFrame({
    'Score' : ['Low', "Low", "Medium", "Medium", "High"]
})

scale_mapper = {
    "Low" : 1,
    "Medium" : 2,
    "High" : 3
}

data = dataframe['Score'].replace(scale_mapper) #replace는 바꾸는 명령어
print(data)


"""
data.replace(".png", "")
하면 확장자가 사라지고 이름만 남음
"""

from sklearn.preprocessing import OrdinalEncoder

feature_array = np.array([['Low', 10],
                          ['High', 40],
                          ['Medium', 3]])

ordinal_encoder = OrdinalEncoder()
ordinal_encoder.fit_transform(feature_array)



# 특성 딕셔너리 인코딩

from sklearn.feature_extraction import DictVectorizer

data_dict = [{"Red": 2, "Blue": 4},
             {"Red": 2, "Blue": 3},
             {"Red": 1, "Yellow": 2},
             {"Red": 1, "Yellow": 2}]

dictVectorizer = DictVectorizer(sparse=False)
feature_dict = dictVectorizer.fit_transform(data_dict)
feature_dict_name = dictVectorizer.get_feature_names_out()

dict_data = pd.DataFrame(feature_dict, columns=feature_dict_name)
print(dict_data)


0    1
1    1
2    2
3    2
4    3
Name: Score, dtype: int64
   Blue  Red  Yellow
0   4.0  2.0     0.0
1   3.0  2.0     0.0
2   0.0  1.0     2.0
3   0.0  1.0     2.0


## 누락된 클래스 값 처리

In [42]:
from sklearn.neighbors import KNeighborsClassifier

x = np.array([[0, 2.10, 1.48],
              [1, 1.18, 1.33],
              [0, 1.22, 1.27],
              [1, -0.2, -1.15]
              ])

x_with_nan = np.array([[np.nan, 0.87, 1.33], [np.nan, -0.67, -0.22]])
clf = KNeighborsClassifier(3, weights='distance')



train_model = clf.fit(x[:,1:], x[:,0])
imputer_values = train_model.predict(x_with_nan[:,1:]) # 누락된 값의 클래스 예측

x_with_imputer = np.hstack((imputer_values.reshape(-1,1), x_with_nan[:,1:]))
data=np.vstack((x_with_imputer, x)) # 두 행렬 연결
print(data)

[[ 0.    0.87  1.33]
 [ 1.   -0.67 -0.22]
 [ 0.    2.1   1.48]
 [ 1.    1.18  1.33]
 [ 0.    1.22  1.27]
 [ 1.   -0.2  -1.15]]


누락된 클래스 값 처리 - 02

In [60]:
from sklearn.impute import SimpleImputer

x_complete = np.vstack((x_with_nan, x))

impute = SimpleImputer(strategy='most_frequent')
data_impute = impute.fit_transform(x_complete)
print(f"처리 전 \n{x_complete}")
print(f"처리 후 \n{data_impute}")

처리 전 
[[  nan  0.87  1.33]
 [  nan -0.67 -0.22]
 [ 0.    2.1   1.48]
 [ 1.    1.18  1.33]
 [ 0.    1.22  1.27]
 [ 1.   -0.2  -1.15]]
처리 후 
[[ 0.    0.87  1.33]
 [ 0.   -0.67 -0.22]
 [ 0.    2.1   1.48]
 [ 1.    1.18  1.33]
 [ 0.    1.22  1.27]
 [ 1.   -0.2  -1.15]]
